### ISSUE TITLE
Twitter/X - Criativo 1 - Warm Up

### ISSUE THREAD

**Issue by JennyT3** [w3b3d3v/StudyGroup#48]
1 post com a programação
reforçar data/lideres e learning outcomes
LInk para inscrição do grupo de estudos

Exemplo de peça:

![Image](https://github.com/w3b3d3v/StudyGroup/assets/98783850/d0a5f0ab-dfb3-4b9c-92e7-21ce6c46985c)

**Comment by JennyT3** [comment]
¿Quieres dominar Stellar y Soroban? 🚀 
Únete a nuestro grupo de estudios en Discord, liderado por expertos como Francisco Catrileo y Joaquín Soza. Aprende a crear wallets, contratos inteligentes y más. ¡Que estás esperando! Empieza el 3 de julio y sigue todos los miércoles a las 11 GMT -3. 
Inscríbete ahora: https://discord.com/invite/4QQNdypNay 🌐🔗
#WEB3 #Blockchain #Stellar #Soroban

**Comment by viniblack** [comment]
https://www.canva.com/design/DAGJQar8MYI/icjK4R7ZT_rLrcl1j7iINg/edit?utm_content=DAGJQar8MYI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

[TwitterX - Criativo 1 - Warm Up.pdf](https://github.com/user-attachments/files/15996188/TwitterX.-.Criativo.1.-.Warm.Up.pdf)

**Comment by JennyT3** [comment]
Falta um último ponto e farei tudo em espanhol.
